version: "2"
services:
    rules1:
        image: chfs/init-edbc:pilot
        extra_hosts:
         - "pilot.kyrules.chfsinet.ky.gov:172.26.130.216"
    rules2:
        image: chfs/init-edbc:pilot
        extra_hosts:
         - "pilot.kyrules.chfsinet.ky.gov:172.26.130.198"
    rules3:
        image: chfs/init-edbc:pilot
        extra_hosts:
         - "pilot.kyrules.chfsinet.ky.gov:172.26.130.199"
    rules4:
        image: chfs/init-edbc:pilot
        extra_hosts:
         - "pilot.kyrules.chfsinet.ky.gov:172.26.130.200"
    rules5:
        image: chfs/init-edbc:pilot
        extra_hosts:
         - "pilot.kyrules.chfsinet.ky.gov:172.26.130.201"
    rules6:
        image: chfs/init-edbc:pilot
        extra_hosts:
         - "pilot.kyrules.chfsinet.ky.gov:172.26.130.232"